### ISSUE TITLE
[FEATURE REQUEST] Support boats

### ISSUE THREAD

**Issue by Oliver-makes-code** [soir20/MoreMcmeta#23]
**Is your feature request related to a problem? Please describe.**
Yes, boats aren't supported

It might be an incompatibility with the Terraform Wood API, I haven't had time to check though

**Which Minecraft versions would this feature apply to?**
1.19.4+

**Additional context**
I need it for the mod I'm developing
![image](https://github.com/soir20/MoreMcmeta/assets/59418903/4b50d64c-81d4-486c-8d40-379189abfc57)

**Comment by soir20** [comment]
Boats should be supported; the issue is likely related to the rectangular shape of the boat texture.

When no frame size is specified, MoreMcmeta assumes the frame is square. This means that textures with rectangular frames will not work correctly if you don't specify a frame size. See the [animation format documentation](https://github.com/soir20/MoreMcmeta/wiki/User-Docs:-Animation-Format#rectangular-frames).

Try adding `"width": 128` and `"height": 64` to the `"animation"` section of your metadata file. (I'm assuming your frames are 128x64 like the default Minecraft texture.)

For example:
```
{
    "animation": {
        "width": 128,
        "height": 64
    }
}
```

Unfortunately, there is not a way to automatically detect the right frame size for rectangular frames.

Please let me know if this does not fix the problem, or close this issue if the problem is resolved.

**Comment by Oliver-makes-code** [comment]
I already tried it with that, the behaviour with width/height specified is what's shown in the screenshot

Normal Boat:
```json
{
  "animation": {
    "frametime": 300,
    "interpolate": true,
    "width": 128,
    "height": 64,
    "frames": [
      0,
      1,
      0,
      2
    ]
  }
}
```
Chest Boat:
```json
{
  "animation": {
    "frametime": 300,
    "interpolate": true,
    "width": 128,
    "height": 128,
    "frames": [
      0,
      1,
      0,
      2
    ]
  }
}
```

**Comment by soir20** [comment]
Thanks for clarifying. I will look into this, as boats should be supported. Could you upload logs from a game session where the issue happened?

**Comment by Oliver-makes-code** [comment]
Here's a log from my development environment:
[latest.log](https://github.com/soir20/MoreMcmeta/files/11525552/latest.log)

Outside of development environment (PrismLauncher):
[latest.log](https://github.com/soir20/MoreMcmeta/files/11525559/latest.log)

**Comment by Oliver-makes-code** [comment]
Just confirmed this issue on Fabric instead of just Quilt, with only moremcmeta and Fabric API
Here's a minimal reproduction resource pack:
[repro.zip](https://github.com/soir20/MoreMcmeta/files/11525580/repro.zip)
I replace the Oak Boat texture with an animated one

**Comment by soir20** [comment]
Thanks for providing the resource pack and logs. You need to use the `.moremcmeta` extension instead of the `.mcmeta` extension.

**Comment by Oliver-makes-code** [comment]
That worked! Thank you!
