### ISSUE TITLE
Crash with Moonlight Library (Cannot read the array length because "buf" is null)

### ISSUE THREAD

**Issue by Starexify** [soir20/MoreMcmeta#35]
**Describe the bug**
Crash.

**To reproduce**
1. Add the mod 'Moremcmeta and it's plugin Emissive'
2. Run Forge Minecraft
4. See crash log: https://pastebin.com/teQHNHqj

**Expected behavior**
Not crash

**Which Minecraft versions does this bug affect?**
1.18.2

**Mod loader**
Which mod loaders does this bug affect?
- [x] Forge
- [ ] Fabric

**Mods list**

**Resource pack**
What resource packs are you using? Please link to them or attach them to this issue.
I attach them if there is an issue with resourcepacks

**Additional context**
On 1.20.1 does the same.

**Comment by soir20** [comment]
This is a bug in the Moonlight Library mod. I'll create an issue or PR on their end.

~~I'm going to leave this open for now because I've been wanting to add an icon to MoreMcmeta's internal pack, and that might mitigate this issue.~~

**Comment by soir20** [comment]
Unfortunately, it doesn't look like adding a pack icon will mitigate the problem. (There might be a new release soon to add one anyway.)

Thanks for reporting this issue. Please see the linked pull requests above and update Moonlight Library once they are merged and a new version is released. You can get status updates on these PRs by subscribing to notifications on the right-hand side. I will close this issue and mark it as transferred since the pull requests have been submitted.

**Comment by soir20** [comment]
I also forgot to mention that you can downgrade to MoreMcmeta 4.1.0 as a workaround until Moonlight fixes this on their end.
