### ISSUE TITLE
Update to 1.20.2

### ISSUE THREAD

**Issue by 5543Mj** [soir20/MoreMcmeta#48]
I've tried this mod by itself (with and without fabric API) and Minecraft would just crash upon trying to run it.
I've tried it on both the latest 1.20.2 (is that the problem?) Fabric and Quilt versions.
I even tried out all of your 1.20.1 versions.

the Bug report I got was...
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_3288$class_7679.<init>(net.minecraft.class_2561, int, net.minecraft.class_7699)'

Exit code 255

please and thank you!

**Comment by soir20** [comment]
~Just to clarify, are you using Minecraft 1.20.1 or 1.20.2?~ MoreMcmeta hasn't updated to 1.20.2 yet, which is very likely the cause of this crash. I'm hoping to get a 1.20.2 update out within the next week or two. In the meantime, you'll need to use Minecraft 1.20.1.

Edited since I missed that in my original read of the issue

**Comment by 5543Mj** [comment]
Ah, thought it might be so. Thanks for letting me know. I await the next update with bated breath.

**Comment by soir20** [comment]
MoreMcmeta v4.4.0 for 1.20.2 has been released. It will take a few minutes for the files to be approved by CurseForge.

Please note that the emissive plugin has not yet updated to 1.20.2; there will be one or two releases with bug fixes before that updates.
