### ISSUE TITLE
Texture is stuck on frame 1.

### ISSUE THREAD

**Issue by googlescientificnameforapig** [soir20/MoreMcmeta#9]
**Describe the bug**
A clear and concise description of what the bug is. The texture is either black or stuck on frame #1. Frame no 1 is black.

**To reproduce**
1. Put on my texture pack
2. Add the mod 'cit resewn, moremcmeta'
4. rename a redstone torch to: "Oh no"

**Expected behavior**
An animated rick roll

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/100143295/166156034-dd51b281-fe75-4879-bedc-277b4b5dea70.png)

**Which Minecraft versions does this bug affect?**
- 1.18

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Fabric

**Mods list**
What mods are you using? 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/100143295/166155502-b0e0913f-4e3b-4ee5-bdc7-784f21cb179f.png">

**Resource pack**
What resource packs are you using? Please link to them or attach them to this issue.
[LOLXD.zip](https://github.com/soir20/MoreMcmeta/files/8599323/LOLXD.zip)

**Additional context**

**Comment by soir20** [comment]
Thanks for attaching the pack and screenshot in your report!

I've identified the cause of the issue. It is a minor incompatibility between MoreMcmeta and CIT Resewn. In short:

- CIT adds your texture to what is called the "texture atlas"--a big collection of textures in one image that Minecraft uses in certain cases, like block textures.
- Minecraft's convention for listing texture names inside the atlas is to omit the .png suffix. However, CIT includes the .png suffix in its texture names.
- MoreMcmeta removes the suffix as it assumes the Minecraft naming convention will hold and checks against the atlas for the texture. Since the suffix is missing, MoreMcmeta doesn't find the texture and assumes it is not a texture on the atlas.
- Because MoreMcmeta treats the texture as if it is not on any texture atlas, the internal handlers that cause animation updates are never triggered.

IMO, it's a simple enough fix on MoreMcmeta's end to do checks with and without the suffix and handle edge cases like this that might show up in other mods. The additional check can be performed efficiently. I may not be able to release a new version until the weekend since I would want to test the new changes.

**Comment by soir20** [comment]
Fixed versions have been released on CurseForge, Modrinth, and GitHub.
